# Generated by Django 3.1.4 on 2022-05-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(blank=True, default='female', max_length=10, verbose_name='性别')),
                ('birthday', models.DateTimeField(blank=True, default=None, null=True, verbose_name='出生日期')),
                ('rule', models.CharField(blank=True, default='shape', max_length=10, verbose_name='形状')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='PlayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, null=True, verbose_name='实验记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simmaster.myuser')),
            ],
            options={
                'db_table': 'playinfo',
            },
        ),
        migrations.DeleteModel(
            name='SimList',
        ),
    ]
