# Generated by Django 3.1.4 on 2024-08-12 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simmaster', '0002_auto_20220517_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_played_ipad',
            field=models.BooleanField(default=False, verbose_name='是否玩过iPad'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='subject_id',
            field=models.CharField(default=-1, max_length=50, verbose_name='被试ID'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='rule',
            field=models.CharField(blank=True, default='shape', max_length=10, verbose_name='规则'),
        ),
        migrations.AlterField(
            model_name='playinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='simmaster.myuser'),
        ),
    ]
